apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: backend-service
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend-service
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: backend-service
                image: example.com/backend-service:dev
commonLabels:
  environment: dev
